### ISSUE TITLE
UI ideas

### ISSUE THREAD

**Issue by otaniyoz** [cmnord/jep#50]
Hi, Claire

I read your blog post about Jep! and tried to solve some of the UI challenges you faced. Here are some screens I designed:
![screens](https://github.com/cmnord/jep/assets/37662409/303b8779-f4eb-4a83-ae3a-f5392b092a68)

In short, I tried to highlight differences from Jeopardy!, while maintaining a sense of familiariaty for the long-time TV show fans: got rid of all-caps, vertical tables, and handwritten names, and emphasised the ability to upload games and have _arbitrary_ number of players, rounds, categories, and clues.

Designs ended up pretty raw in places, as I only wanted to test out some ideas. But main points are clear, I guess. If you want, I could probably make adjustments based on your feedback or share the Figma file with you ¯\\\_(ツ)\_/¯

Anyway, Jep! is great, thanks for making it  ( saying this as a QI fan :-) )

**Comment by cmnord** [comment]
Hi, thanks so much for these designs! I hope you've enjoyed playing some games as well.

What are your goals for this redesign?
- I feel like the grid board design is pretty good as-is and is flexible enough to suit custom numbers of categories x clues.
- I don't find the number of games uploaded super useful; is it to encourage people to upload new games?

In general, the ratio of puzzle-players to puzzle-makers is really high, so I don't think focusing even more on puzzle-makers on the home page is useful. I'm planning to focus on puzzle-players until I meet enough puzzle-makers to understand their needs and get feedback from them.

My biggest design challenge right now is game momentum / clarity. How can we make it clearer what action is required from you to keep the game moving fast?

Some transitions that are kind of slow right now:
  - you won the buzz and need to answer
  - the last buzzer was wrong and you can jump in to buzz again
  - you need to choose the next clue

Given this, I think it's worth considering redesigns of the "in-clue" experience and transitions in and out of it. I'll make a separate GitHub issue which outlines this.

**Comment by otaniyoz** [comment]
Thanks for your comments. I agree with every point you made. 

In general, I opened this issue to explore some design ideas and narrow down on the ones you find worth considering. You addressed just that -- despite my efforts at miscommunicating everything -- so this issue can be closed.

Should I close it or do you want to keep it as a thread for possible design ideas?

**Comment by cmnord** [comment]
Closed in favor of #53
